version: '2'

services:
  db:
    image: postgres
    volumes:
      - ghtsdata:/var/lib/postgresql/data
      - ./syria.sql:/docker-entrypoint-initdb.d/syria.sql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/src"
    ports:
      - "80:80"
    depends_on:
     - db
     
volumes:
  ghtsdata:
    external: true
