version: '2'

services:
  db:
    image: postgres
    volumes:
      - ghtsdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/src"
    ports:
      - "9999:9999"
    depends_on:
     - db
     
volumes:
  ghtsdata:
    external: true