# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20170901_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='appeal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='appeal_status',
            field=models.CharField(blank=True, choices=[('P', 'Amount pledged for appeal'), ('V', 'How much of the appeal pledge via conference pledge'), ('C', 'Contributions for appeal so far'), ('H', 'Contributions via appeal part of conference pledge')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='multiyear_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
