# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-24 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20171212_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='appeal_status',
            field=models.CharField(blank=True, choices=[('P', 'Amount pledged for appeal'), ('V', 'How much of the appeal pledge via conference pledge'), ('C', 'Contributions for UN-coordinated appeals so far'), ('H', 'Contributions via appeal part of conference pledge')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='refugee_facility_for_turkey',
            field=models.CharField(blank=True, choices=[('L', 'Contributions to Facility for Refugees in Turkey'), ('N', 'Contributions to Turkey excluding those to the Facility for Refugees in Turkey')], max_length=1, null=True),
        ),
    ]
