# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-30 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20180130_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='facility',
            field=models.CharField(blank=True, choices=[('T', 'Facility for Refugees in Turkey'), ('R', 'EU Regional Trust Fund in response to the Syrian crisis'), ('M', 'Global Concessional Financing Facility')], max_length=1, null=True),
        ),
    ]
