# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20180130_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheet',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
